globalConfig:
  secret:
    stringData:
      client: "irodsfuse"
      host: "data.cyverse.org"
      port: "1247"
      zone: "iplant"
      user: "adminuser"
      password: "password"
      enforceProxyAccess: "true"
      poolEndpoint: "tcp://irodsfs-pool.example.org:12020"
      mountPathWhitelist: "/iplant/home"